### ISSUE TITLE
Patching PyNN is unnecessary

### ISSUE THREAD

**Issue by conradtchan** [ADACS-Australia/neuron-dbs-model#1]
The patch contains changes to 4 files:
- common/common.py
- neuron/__init__.py
- neuron/simulator.py
- neuron/standardmodels/electrodes.py

The differences are very small. Patching the PyNN package is not a good long term solution, because it:
- Requires an unorthodox installation method
- Will likely break with future releases of PyNN

Alternatives are either:
- Fork PyNN and create (and optionally, create a PR with these new features)
- Write a separate package that derives from the PyNN classes

**Comment by dliptai** [comment]
Simplified patching in #9
