### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by conradtchan** [ADACS-Australia/neuron-dbs-model#2]
To-do:

Questions:
`simulation_duration` is used to set the simulation time. This is set to 6000 (`steady_state_duration`). 
- How is it determined that 6000 seconds produces a steady state?
- Is there additional convergence criteria?
- [docs](https://senselab.med.yale.edu/ModelDB/ShowModel?model=262046&file=/Cortex_BasalGanglia_DBS_model/readme.html#tabs-2) suggest that this should be 6s instead. Is this consistent?

Code depends on `mpi4py`
- Does running with `mpirun` do anything other than run the code `n` times? It doesn't seem like it. It would be hard to tell anyway, because the code always runs until the wall time limit.

NEURON does have some kind of MPI support: https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html

Proposed tasks:
- Refactor code (#1)

**Comment by silvanx** [comment]
I've figured out why running the code with mpirun doesn't result in a speedup.

The `from mpi4py import MPI` line needs to be placed **before** `from pyNN.neuron import simulator`

**Comment by dliptai** [comment]
Yep I figured the same thing out the other day! It's in the latest version of the code. No longer need to use `nrniv` :)
